# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='a_name',
            new_name='articleName',
        ),
        migrations.RenameField(
            model_name='tutorialmodel',
            old_name='t_name',
            new_name='tutorialName',
        ),
    ]
