# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20170909_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialmodel',
            old_name='t_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='tutorialmodel',
            name='t_url',
        ),
    ]
